// Brand colors -- intentionally desaturated where they overlap brand identity isn't needed.
window.BRAND_COLORS = {
  Amazfit: "#00BCD4",
  Apple: "#A8A8A8",
  Coros: "#8BC34A",
  Garmin: "#E53935",
  Google: "#FBBC04",
  Huawei: "#7B1FA2",
  "Eight Sleep": "#E91E8C",
  Other: "#333333",
  Oura: "#FF69B4",
  Polar: "#FF9800",
  Samsung: "#9C27B0",
  Suunto: "#3F51B5",
  Whoop: "#1565C0",
  Xiaomi: "#4CAF50",
};

// Human-readable display names (replaces underscores / camelCase).
window.prettyName = function (raw) {
  return raw
    .replace(/_/g, " ")
    .replace(/([a-z])([A-Z0-9])/g, "$1 $2")
    .replace(/\s+/g, " ")
    .trim();
};

window.HR_DATA = [
  // Top performers (from filtered >0.90 chart)
  { name: "WahooTrackrHrm", brand: "Other", r: 1.00 },
  { name: "AppleWatch11_46", brand: "Apple", r: 0.99 },
  { name: "AmazfitHelioStrap_biceps", brand: "Amazfit", r: 0.99 },
  { name: "AmazfitHelioSleeve", brand: "Amazfit", r: 0.99 },
  { name: "AppleWatchSE2025", brand: "Apple", r: 0.98 },
  { name: "PixelWatch4_41mm", brand: "Google", r: 0.98 },
  { name: "HuaweiWatchGT6", brand: "Huawei", r: 0.98 },
  { name: "AppleWatchUltra3", brand: "Apple", r: 0.98 },
  { name: "PolarLoop_biceps", brand: "Polar", r: 0.97 },
  { name: "MiBand10", brand: "Xiaomi", r: 0.97 },
  { name: "GarminForerunner970", brand: "Garmin", r: 0.96 },
  { name: "AmazfitHelioStrap_special", brand: "Amazfit", r: 0.96 },
  { name: "GarminForerunner570", brand: "Garmin", r: 0.96 },
  { name: "HuaweiWatchFit4", brand: "Huawei", r: 0.95 },
  { name: "AmazfitHelioStrap_wrist", brand: "Amazfit", r: 0.95 },
  { name: "GalaxyWatchUltra2_2025", brand: "Samsung", r: 0.95 },
  { name: "AmazfitTrex3Pro_44mm", brand: "Amazfit", r: 0.94 },
  { name: "SuuntoRace2", brand: "Suunto", r: 0.94 },
  { name: "AmazfitActive3Premium", brand: "Amazfit", r: 0.94 },
  { name: "AmazfitBalance2", brand: "Amazfit", r: 0.94 },
  { name: "AmazfitActiveMax", brand: "Amazfit", r: 0.94 },
  { name: "HuaweiWatchFit4Pro", brand: "Huawei", r: 0.94 },
  { name: "PowerbeatsProBiceps", brand: "Apple", r: 0.93 },
  { name: "PolarGritX2", brand: "Polar", r: 0.93 },
  { name: "HuaweiBand11Pro", brand: "Huawei", r: 0.93 },
  { name: "WhoopMG_biceps", brand: "Whoop", r: 0.93 },
  { name: "GarminVenu4", brand: "Garmin", r: 0.93 },
  { name: "CorosPace4", brand: "Coros", r: 0.92 },
  { name: "AppleAirPodsPro3", brand: "Apple", r: 0.92 },
  { name: "GalaxyWatch8_2025", brand: "Samsung", r: 0.92 },
  { name: "GarminInstinct3", brand: "Garmin", r: 0.91 },
  { name: "OneplusWatch3", brand: "Other", r: 0.90 },
  // Lower performers (from full chart)
  { name: "Loop_autoDetect", brand: "Other", r: 0.700 },
  { name: "HuaweiBand11_first", brand: "Huawei", r: 0.740 },
  { name: "Watch4_45mm", brand: "Samsung", r: 0.790 },
  { name: "OuraRing4", brand: "Oura", r: 0.795 },
  { name: "HuaweiBand10_second", brand: "Huawei", r: 0.800 },
  { name: "PolarA300", brand: "Polar", r: 0.802 },
  { name: "AmazfitDevice", brand: "Amazfit", r: 0.804 },
  { name: "GarminVivoactive6", brand: "Garmin", r: 0.820 },
  { name: "GarminTrex_Classic_Pro", brand: "Garmin", r: 0.828 },
  { name: "AmazfitTrex_Ultra2", brand: "Amazfit", r: 0.832 },
  { name: "SuuntoVertical2", brand: "Suunto", r: 0.835 },
  { name: "CmtWatch3_second", brand: "Other", r: 0.838 },
  { name: "GalaxyWatch8_Classic", brand: "Samsung", r: 0.840 },
  { name: "HuaweiWatch_Ultimate", brand: "Huawei", r: 0.844 },
  { name: "AmazfitBip5", brand: "Amazfit", r: 0.847 },
  { name: "WhoopVoyager", brand: "Whoop", r: 0.848 },
  { name: "GalaxyWatch3", brand: "Samsung", r: 0.855 },
  { name: "SuuntoOcean_second", brand: "Suunto", r: 0.858 },
  { name: "GalaxyWatch5", brand: "Samsung", r: 0.861 },
  { name: "AmazfitActive4", brand: "Amazfit", r: 0.868 },
  { name: "PowerbeatsProForearm", brand: "Apple", r: 0.870 },
  { name: "HuaweiWatch3", brand: "Huawei", r: 0.872 },
  { name: "AppleWatch3", brand: "Apple", r: 0.875 },
  { name: "GarminForerunner55", brand: "Garmin", r: 0.878 },
  { name: "GalaxyWatchFE", brand: "Samsung", r: 0.880 },
  { name: "SuuntoRace2_old", brand: "Suunto", r: 0.883 },
  { name: "AmazfitBip5Ultra", brand: "Amazfit", r: 0.885 },
  { name: "HuaweiWatchGT4Pro", brand: "Huawei", r: 0.888 },
  { name: "AmazfitHaloStrap_Wrist", brand: "Amazfit", r: 0.890 },
  { name: "AmazfitBip5_second", brand: "Amazfit", r: 0.892 },
  { name: "GarminForerunner570_old", brand: "Garmin", r: 0.895 },
  { name: "AmazfitHaloStrap_special_old", brand: "Amazfit", r: 0.897 },
  { name: "GarminForerunner_570", brand: "Garmin", r: 0.900 },
  { name: "GalaxyWatch6Classic", brand: "Samsung", r: 0.903 },
  { name: "HuaweiWatchGT5", brand: "Huawei", r: 0.905 },
  { name: "AmazfitT_Rex3_Strap", brand: "Amazfit", r: 0.908 },
  { name: "CmtWatch3Pro", brand: "Other", r: 0.912 },
  { name: "AmazfitActive5", brand: "Amazfit", r: 0.915 },
  { name: "WhoopBiceps", brand: "Whoop", r: 0.918 },
  { name: "GarminStreet", brand: "Garmin", r: 0.922 },
  { name: "WhoopBand5Biceps", brand: "Whoop", r: 0.924 },
  { name: "SuuntoVertical_second", brand: "Suunto", r: 0.926 },
  { name: "HuaweiWatch4Pro", brand: "Huawei", r: 0.928 },
  { name: "AmazfitActive6", brand: "Amazfit", r: 0.930 },
  { name: "GarminFenix8", brand: "Garmin", r: 0.932 },
  { name: "GarminForerunner265", brand: "Garmin", r: 0.934 },
  { name: "GarminFenix8_second", brand: "Garmin", r: 0.936 },
  { name: "GarminForerunnerMax", brand: "Garmin", r: 0.938 },
  { name: "GalaxyWatch7", brand: "Samsung", r: 0.940 },
  { name: "AmazfitHaloStrap2025", brand: "Amazfit", r: 0.942 },
  { name: "CorosVertix3", brand: "Coros", r: 0.944 },
  { name: "AmazfitHaloSleeve", brand: "Amazfit", r: 0.948 },
  { name: "Pixel9Pro", brand: "Google", r: 0.952 },
  { name: "AmazfitHaloBiceps", brand: "Amazfit", r: 0.955 },
  { name: "WahooTickrFitBiceps", brand: "Other", r: 0.960 },
  { name: "UMband10", brand: "Other", r: 0.962 },
  { name: "GarminHRMPro", brand: "Garmin", r: 0.964 },
  { name: "WahooTickrHrm", brand: "Other", r: 0.968 },
  { name: "AmazfitHaloStrip2025", brand: "Amazfit", r: 0.970 },
  { name: "Biceps_401", brand: "Other", r: 0.973 },
  { name: "Polar_H10", brand: "Polar", r: 0.976 },
  { name: "GarminHRM_Pro_Plus", brand: "Garmin", r: 0.979 },
  { name: "Apple_chest", brand: "Apple", r: 0.982 },
].sort((a, b) => a.r - b.r).map((d, i) => ({ ...d, rank: i + 1 }));

window.SLEEP_DATA = [
  { name: "AppleWatchUltra3", brand: "Apple", score: 76.0, kappa: 0.72, sensitivity: 80 },
  { name: "EightSleepPod5", brand: "Eight Sleep", score: 75.0, kappa: 0.70, sensitivity: 80 },
  { name: "WhoopMG_biceps", brand: "Whoop", score: 71.5, kappa: 0.65, sensitivity: 78 },
  { name: "AppleWatch11_46", brand: "Apple", score: 70.0, kappa: 0.68, sensitivity: 72 },
  { name: "PixelWatch4_45mm", brand: "Google", score: 67.5, kappa: 0.65, sensitivity: 70 },
  { name: "PixelWatch4_41mm", brand: "Google", score: 66.5, kappa: 0.63, sensitivity: 70 },
  { name: "GalaxyWatch8_2025", brand: "Samsung", score: 65.0, kappa: 0.62, sensitivity: 68 },
  { name: "GalaxyWatchUltra2_2025", brand: "Samsung", score: 64.0, kappa: 0.60, sensitivity: 68 },
  { name: "OuraRing4_ceramic", brand: "Oura", score: 62.5, kappa: 0.58, sensitivity: 67 },
  { name: "GarminFr570_biceps", brand: "Garmin", score: 62.5, kappa: 0.57, sensitivity: 68 },
  { name: "AmazfitHelioStrap_special", brand: "Amazfit", score: 61.5, kappa: 0.56, sensitivity: 67 },
  { name: "GalaxyWatch8_classic_2025", brand: "Samsung", score: 60.0, kappa: 0.55, sensitivity: 65 },
  { name: "AmazfitActiveMax", brand: "Amazfit", score: 59.5, kappa: 0.54, sensitivity: 65 },
  { name: "AmazfitTrex3Pro", brand: "Amazfit", score: 58.5, kappa: 0.53, sensitivity: 64 },
  { name: "GarminVenu4", brand: "Garmin", score: 57.5, kappa: 0.52, sensitivity: 63 },
  { name: "GarminInstinct3", brand: "Garmin", score: 56.5, kappa: 0.51, sensitivity: 62 },
  { name: "SuuntoVertical2", brand: "Suunto", score: 56.0, kappa: 0.50, sensitivity: 62 },
  { name: "GarminVenuX1", brand: "Garmin", score: 55.5, kappa: 0.50, sensitivity: 61 },
  { name: "AmazfitTrexUltra2", brand: "Amazfit", score: 55.5, kappa: 0.49, sensitivity: 62 },
  { name: "AmazfitHelioStrap_biceps", brand: "Amazfit", score: 55.0, kappa: 0.49, sensitivity: 61 },
  { name: "MiBand10", brand: "Xiaomi", score: 54.5, kappa: 0.48, sensitivity: 61 },
  { name: "CmtWatch3Pro", brand: "Other", score: 54.0, kappa: 0.48, sensitivity: 60 },
  { name: "PolarGritX2", brand: "Polar", score: 53.5, kappa: 0.47, sensitivity: 60 },
  { name: "GarminForerunner970", brand: "Garmin", score: 52.5, kappa: 0.46, sensitivity: 59 },
  { name: "GarminForerunner570", brand: "Garmin", score: 52.5, kappa: 0.46, sensitivity: 59 },
  { name: "AmazfitActive2", brand: "Amazfit", score: 51.5, kappa: 0.45, sensitivity: 58 },
  { name: "AmazfitBalance2", brand: "Amazfit", score: 51.0, kappa: 0.44, sensitivity: 58 },
  { name: "OneplusWatch3", brand: "Other", score: 50.5, kappa: 0.44, sensitivity: 57 },
  { name: "PolarLoop_biceps", brand: "Polar", score: 50.0, kappa: 0.43, sensitivity: 57 },
  { name: "PolarLoop_autoDetect", brand: "Polar", score: 49.5, kappa: 0.43, sensitivity: 56 },
  { name: "PolarLoop_onDevice", brand: "Polar", score: 49.0, kappa: 0.42, sensitivity: 56 },
  { name: "HuaweiWatchFit4", brand: "Huawei", score: 48.5, kappa: 0.41, sensitivity: 56 },
  { name: "HuaweiBand11Pro", brand: "Huawei", score: 47.5, kappa: 0.40, sensitivity: 55 },
  { name: "MotoWatch", brand: "Other", score: 46.5, kappa: 0.39, sensitivity: 54 },
  { name: "HuaweiWatchGT6", brand: "Huawei", score: 45.5, kappa: 0.38, sensitivity: 53 },
  { name: "HuaweiBand11_second", brand: "Huawei", score: 44.5, kappa: 0.37, sensitivity: 52 },
  { name: "HuaweiBand11_first", brand: "Huawei", score: 43.5, kappa: 0.35, sensitivity: 52 },
  { name: "HuaweiWatchGT6Pro", brand: "Huawei", score: 42.5, kappa: 0.34, sensitivity: 51 },
  { name: "CorosPace4", brand: "Coros", score: 41.5, kappa: 0.33, sensitivity: 50 },
  { name: "HuaweiBand10_black", brand: "Huawei", score: 39.0, kappa: 0.30, sensitivity: 48 },
  { name: "HumeBand", brand: "Other", score: 37.0, kappa: 0.28, sensitivity: 46 },
  { name: "HuaweiWatch5", brand: "Huawei", score: 36.5, kappa: 0.27, sensitivity: 46 },
  { name: "HuaweiWatchGTRunner2", brand: "Huawei", score: 35.0, kappa: 0.25, sensitivity: 45 },
].sort((a, b) => b.score - a.score).map((d, i) => ({ ...d, rank: i + 1 }));

window.badgeFor = function (mode, value) {
  if (mode === "hr") {
    if (value >= 0.95) return { label: "EXCELLENT", tone: "ok" };
    if (value >= 0.90) return { label: "GOOD", tone: "good" };
    return { label: "FAIR", tone: "fair" };
  }
  if (value >= 65) return { label: "EXCELLENT", tone: "ok" };
  if (value >= 50) return { label: "GOOD", tone: "good" };
  return { label: "FAIR", tone: "fair" };
};
